### ISSUE TITLE
report of roads missing from map.

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#102]
"For example the road running south east out of Blemish exists, but is not on the map whilst in the game. North of violet home there is a road that runs north to the border, but isnt on the ingame map."

**Comment by philipdiehl1** [comment]
This sounds like a normal game bug.  If someone can post some screenshots of the issue I can pass it along for it to be investigated.

**Comment by meowNIman** [comment]
![terminus map report](https://user-images.githubusercontent.com/79648109/167337605-58e63d1a-cd26-4db4-82d7-1fac2defb52d.png)
Terminus Therezio
road that dont exist ( under G house)
( its intel map but those ghouses are well known and built before war so this is not an intel leak)

**Comment by philipdiehl1** [comment]
All maps were updated for v0.50.  If issues like this persist, please pass along the information using the usual Foxhole bug report channels.
