### ISSUE TITLE
[BUG] "If-None-Match" sent as anything but string it breakes.

### ISSUE THREAD

**Issue by flan6** [clapfoot/warapi#105]
In Go all Headers are maped as `map[string][]string` this means all headers sent are included in a list of strings.
So when you add the header with the Etag value it became: `"If-None-Match": ["42"]` and the api breaks and return 500.
Making it impossible to utilize the headers in go.

Steps to reproduce:

request anything cache-able with the header "If-None-Match" with any value other than a single string

**Comment by Yin117** [comment]
This kinda sounds like an issue with "go" more than an issue with the API?

So more a change request?

**Comment by flan6** [comment]
found a solution:
```go
client := &http.Client{}
req, err := http.NewRequest("GET", "http://example.com", nil)
req.Header.Set("If-None-Match", `"abc123"`)
resp, err := client.Do(req)
```

Stated by chatGPT:
> It's worth noting that the "If-None-Match" HTTP header field is used with a method to make it conditional. When used with the GET method, the server will send the requested resource, with a 200 status, only if it doesn't have an ETag matching the given ones. If the ETag matches, the server will respond with a 304 status, without sending the resource. Also, the value of the header should be surrounded by double quotes, that's why "abc123" is used instead of abc123.
It's also important to make sure that the variable that you use to set the header value is a string, and it has the right format and value that the server is expecting.

So in my case it bacame:
```go
	if etag := entity.Etag(); etag != "" {
		req.Header.Set("If-None-Match", fmt.Sprintf(`"%s"`, etag))
	}
```
