### ISSUE TITLE
Add note to readme about isScorched for nuked rocket sites.

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#106]
It should be noted that if a rocket site is nuked, the only way to determine if it is launched or nuked is if it has the owner flag set afterward. None means was nuked, a TeamId means it was launched.

**Comment by philipdiehl1** [comment]
It's already there.  From the readme:

> Rocket launches
> Each Rocket Site is a one time use launch site for Rockets. When a Rocket is launched, the Rocket Site will become scorched, and its team id will be set to the faction that initiated the Rocket launch.
> 
> This means that you can determine that a Rocket has launched based on the following conditions:
> 
> iconType is set to Rocket Site (37). See [Map Icons](https://github.com/clapfoot/warapi#map-icons)
> teamId is set to COLONIALS or WARDENS. See [Map Data Schema](https://github.com/clapfoot/warapi#map-data-schema)
> flags has IsScorched set. See [Map Flags](https://github.com/clapfoot/warapi#map-flags)

The exact 3 conditions are listed there.

**Comment by hayden-t** [comment]
well yeah i kinda does say that without saying it, could be clearer:
"This means that you can determine that a Rocket has launched rather than destroyed based on the following conditions: "
