### ISSUE TITLE
More map intel that could be published publically

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#107]
So some/all of the intel (map icons etc) that is detected by both sides could be shown publicly via the api. this would be enough to be able to show the current front line position.

**Comment by Yin117** [comment]
What intel were you thinking, as I believe everything public in-game, is already in the API, no?

**Comment by hayden-t** [comment]
you are missing my idea, what im suggesting is that radio intel that would normally be private, could be made public if it is detected/known by both sides

**Comment by Yin117** [comment]
I see your point, but that would expose that say Colonials have Listening Kits or Intel Centers targeting said locations, or Watch Towers; making private infornation, public.

Making stuff Privatly known to both, is still exposing private informstion.

**Comment by hayden-t** [comment]
yeah, i had this idea a long time ago, and it wouldnt work no wth those things you mentioned...
