### ISSUE TITLE
Building some Structures leads to disappearance from API

### ISSUE THREAD

**Issue by Yin117** [clapfoot/warapi#108]
No explanation needed, take a screenshot:
![image](https://user-images.githubusercontent.com/5795461/225974638-409b7d0f-964e-43f1-8a8b-3d000119ff97.png)
Around <t:1679073300:F> `<t:1679073300:F>` (Discord) or `2023-03-17T17:15:00.000Z` ISO

Back not long after:
![image](https://user-images.githubusercontent.com/5795461/225975687-bd44ac4e-d8a6-4c5e-a5f8-f06703c5d113.png)

**Comment by Yin117** [comment]
![image](https://user-images.githubusercontent.com/5795461/225975062-306f1b08-cb54-495f-b26f-f20ab21772b9.png)
![image](https://user-images.githubusercontent.com/5795461/225975082-ccf0cda3-a775-4010-b352-6d2c785895c4.png)

**Comment by Yin117** [comment]
My Friend suggested something interesting, a change was made to prevent the tapping of structures, is this perhaps having an impact on structures disappearing from the War API?

**Comment by philipdiehl1** [comment]
It's possible the build site state for mines isn't properly showing on the map atm.  I'll investigate a fix when I get a chance, but if anyone can verify my theory is correct definitely post here as it'll make the fix quicker.

**Comment by Yin117** [comment]
> It's possible the build site state for mines isn't properly showing on the map atm. I'll investigate a fix when I get a chance, but if anyone can verify my theory is correct definitely post here as it'll make the fix quicker.

I believe this is the case, my first screenshot collaborates this belief; at around 5:15pm UK time (UTC+0) I had an alert of a removed Salvage Mine in Allod's, with confirmation 3 minutes later by a Member of NCAP/15MIN that they built it, and it is indeed not missing, and not long after (as my bot checks every 10mins) the mine was back.

**Comment by philipdiehl1** [comment]
This was hotfixed today.

**Comment by Yin117** [comment]
The last log of my bot is Yesterday at 18:20 UTC+1 so I believe this has been resolved, thabks for the quick work.

Time to nuke some of my database 🤣
