### ISSUE TITLE
Naval Update - Assets and Data

### ISSUE THREAD

**Issue by Yin117** [clapfoot/warapi#111]
Hello,

I am writing to you here because the turnaround time from Update Announcement to Update Deployment, is often very short, and as we've now found, the turnaround time is 21 days.

I ask here, can we **ahead of time** get new map images for all 43 Regions, and the new Hex Name; based on e.g. `AllodsBightHex` I am guessing the new region will be identified as `StemaLandingHex` and the returning 5 other regions will retain their old names.

Thank you,
Yinoguns

**Comment by Yin117** [comment]
oh, and any other changes, such as do Battleships, Rockets, etc, appear in the War API, and what their new Ids are.

**Comment by hayden-t** [comment]
we are always low priority and will most likely only get update after release :(

**Comment by Opa-** [comment]
![image](https://github.com/clapfoot/warapi/assets/6153672/5ef0e11d-f521-4761-8403-8ced4461a836)

There's definitely new icons coming.
Can guess from top to bottom :

- Landing Ship icon
- Offshore platform
- Nuke site without nuke
- Targeted area by nuke
- Landed nuke
- Nuke site with nuke ready
- ?
- Dry docks
- Ship on intel

Checking the API https://war-service-dev.foxholeservices.com/api when devbranch is live tomorrow is the best option while waiting API doc updated ;)

**Comment by Yin117** [comment]
Breakdown of the Map Changes
![image](https://github.com/clapfoot/warapi/assets/5795461/569215bf-2baa-461d-9f83-954ddf0cdd80)

**Comment by philipdiehl1** [comment]
It was updated today.

**Comment by hayden-t** [comment]
thanks @philipdiehl1 , appreciate you guys getting this out before the update drops
