### ISSUE TITLE
Confirm viewDirection

### ISSUE THREAD

**Issue by Yin117** [clapfoot/warapi#112]
Hello, one small question, the Dev Branch API (dynamic map) is exposing a new property `viewDirection` as highlighted on the Diacord here: https://discord.com/channels/203512636556574720/1161320236746809344/1161414757719478412

Can you confirm if this is intended and will be included in production.

And if so, clarify the meaning of Zero, Positive, and Negative Integers for this value (and add to the README).

Thank you.

**Comment by philipdiehl1** [comment]
This will be hidden from the WarAPI when time permits.  Generally it is not recommended to rely on anything that isn't documented in the README
