### ISSUE TITLE
Naval Update: Further changes?

### ISSUE THREAD

**Issue by Yin117** [clapfoot/warapi#113]
Hello again,

It has been raised in the [Discord](https://discord.com/channels/203512636556574720/523401134107525121/1161911519261495356) that some assets are still missing, or changes left out; Kalokai in particular.

![Screenshot_20231012_072615_Discord](https://github.com/clapfoot/warapi/assets/5795461/a3c08bb1-454b-4c63-9459-a4d35e3b3726)

May I recommend this Issue remains open until all changes of Assets and Data are finalised and complete.

An open ticket with a task, is better than a forgotten closed one.

**Comment by Yin117** [comment]
I also note that in [Map Icons](https://github.com/clapfoot/warapi/tree/master/Images/MapIcons) that there is no icon for the new **Facility Mine Oil Rig**

**Comment by philipdiehl1** [comment]
Thanks, I added the oil rig map icon.  There seem to still be several map image issues which the level designers should be fixing sooner rather than later.

**Comment by philipdiehl1** [comment]
Map images were updated today.
