### ISSUE TITLE
Incorrect Image: MapFishermansRowHex.TGA

### ISSUE THREAD

**Issue by Yin117** [clapfoot/warapi#114]
Hi again,

The Fisherman's Row image is the old bridge image, not the new islands image.

Here is the islands one:
![MapFishermansRowHex](https://github.com/clapfoot/warapi/assets/5795461/cb9c9cab-562d-46a9-9a94-559b016897d0)

**Comment by philipdiehl1** [comment]
Thanks, two maps were reverted due to being incorrectly generated for the time being.
