### ISSUE TITLE
Charlie (Live-3) endpoint undocumented

### ISSUE THREAD

**Issue by reilem** [clapfoot/warapi#118]
I've had users of my app complaining there was no information for the Charlie servers.I was telling them there was nothing I could do since it was not listed here as an endpoint. However, I decided to just try to access the Live-3 (Charlie) API endpoint (`GET https://war-service-live-3.foxholeservices.com/api/worldconquest/war`) and discovered it actually does, exist despite it not being documented in the README.

It would be nice if this could be added to the README for future developers.

**Comment by philipdiehl1** [comment]
Added, thanks.
