### ISSUE TITLE
Question - Rocket Paused Targetting

### ISSUE THREAD

**Issue by Yin117** [clapfoot/warapi#119]
According to the Change notes, Rocket launches can be halted:

> - The Rocket, Rocket Site or the active Listening Center can be destroyed.
>   - Rockets no longer drop anything when they are destroyed.
> - Visibly damaging the Rocket will delay a Rocket launch until it is repaired.

If a Rocket Target is paused in this manner, will the Rocket Target persist, or disappear from the Map/WarAPI?

**Comment by philipdiehl1** [comment]
The Rocket Target map icon will persist.
