### ISSUE TITLE
Text labels appear in the API twice

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#13]
![capture](https://user-images.githubusercontent.com/1000743/39562292-420630ba-4eee-11e8-9cad-46a369e2fcd6.JPG)

**Comment by philipdiehl1** [comment]
Let me know what region this is in and I'll take a look.

**Comment by hayden-t** [comment]
this still happening, but also there are others: https://war-service-live.foxholeservices.com/api/worldconquest/maps/Westgate/static/
![image](https://user-images.githubusercontent.com/1000743/53306667-34bcd400-38e4-11e9-8076-5c7a3bff75bd.png)

**Comment by philipdiehl1** [comment]
The level designers have what they need to fix this.  This will be addressed over time but I'm leaving this open for now as I don't know if everything has been updated yet.

**Comment by hayden-t** [comment]
still happening in hex https://war-service-live.foxholeservices.com/api/worldconquest/maps/WestgateHex/static/

**Comment by hayden-t** [comment]
https://war-service-live.foxholeservices.com/api/worldconquest/maps/GodcroftsHex/static/

**Comment by hayden-t** [comment]
i checked all but top and bottom 3 maps (disabled) and no other duplicates, so not  a big problem

**Comment by philipdiehl1** [comment]
If this is still occurring please let me know and I'll talk to the level designers as this really should be fixed by now since it's gone on long enough.

**Comment by hayden-t** [comment]
still happening 
![image](https://user-images.githubusercontent.com/1000743/89947755-52acfe80-dc68-11ea-8f71-10ec16682a54.png)
https://war-service-live.foxholeservices.com/api/worldconquest/maps/WestgateHex/static/

**Comment by philipdiehl1** [comment]
I've made internal issues for this as there's been plenty of time to fix these.  Westgate and Godcrofts are known to have duplicates so if there are any others, please post them here and they'll be fixed.

**Comment by philipdiehl1** [comment]
This has been addressed for update 41.
