### ISSUE TITLE
MacConmara Barrows typo in API ( \t "Tab" char)

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#14]
![capture](https://user-images.githubusercontent.com/1000743/39562392-cf6381a6-4eee-11e8-9456-4dd94a02268b.JPG)

**Comment by philipdiehl1** [comment]
Post the region and I'll take a look.

**Comment by hayden-t** [comment]
just checked this and its still there: https://war-service-live.foxholeservices.com/api/worldconquest/maps/MooringCounty/static/

**Comment by hayden-t** [comment]
i believe this has flowed through to the game from some reports ive seen

**Comment by philipdiehl1** [comment]
This should be fixed for update 28.

**Comment by KrazyFlyinChicken** [comment]
CL 27104
