### ISSUE TITLE
WorldMap_Color.tga needs 0.14 version uploaded

### ISSUE THREAD

**Issue by S-i-r** [clapfoot/warapi#18]
WorldMap_Color.tga still shows the 0.13 world map.

**Comment by hayden-t** [comment]
yes i noticed this, does not have oarbreaker on it

**Comment by reilem** [comment]
You guys might be interested in this: https://drive.google.com/drive/folders/1b9icIV5Qo_U9OPKJs0V_cztHxhSX2NcY The updated world map is on here.

**Comment by philipdiehl1** [comment]
Should be fixed now.
