### ISSUE TITLE
Obfuscate the player information so player names are not shown

### ISSUE THREAD

**Issue by KrazyFlyinChicken** [clapfoot/warapi#21]
Players are using this to find out what clans are in which regions.

**Comment by hayden-t** [comment]
its not a bug, its a feature :) not though ive removed it from my site now (individual map player name lists)

**Comment by hayden-t** [comment]
One option to mitigate this problem would be to implement clan tag support for the game. such that the game appends your clan tag setting in the game to your steam name, this way possibly reported player names wont have clan tags and be much harder to work out who's where in numbers.

**Comment by hayden-t** [comment]
this can be closed now that steam api is essentially not operating/ supported any more
