### ISSUE TITLE
Westgate Keep missing Icon and Mention in readme: Icon Type #2

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#25]
This is in the API, there is just no mention of it here or icon for it.
![image](https://user-images.githubusercontent.com/1000743/45990563-3af41d80-c0c4-11e8-94ee-30c13ae8552e.png)

**Comment by hayden-t** [comment]
https://github.com/clapfoot/warapi/issues/19

**Comment by philipdiehl1** [comment]
This was a bug.  Thanks for posting this.  It should be fixed now.
