### ISSUE TITLE
Need World Map and web compatible file formats for images

### ISSUE THREAD

**Issue by ROMB** [clapfoot/warapi#3]
As title says.
There is no world map in the images published. And all images are in TGA format, which is not optimal for use on the web.

**Comment by sagitta-ignis** [comment]
I can't help for World Map image but TGA format can be converted with tools like [TGA Viewer](http://tgaviewer.com/). I don't mind creating a pull request with jpeg/png files but the repository is already over 100 Mo 😀

**Comment by hayden-t** [comment]
Yes a world map image would be good. the images are the way they are as thats how they came out of the game. and they just wanted to get it done.

**Comment by hayden-t** [comment]
here is world map:
[bgTravelScreen.zip](https://github.com/clapfoot/warapi/files/1958283/bgTravelScreen.zip)

**Comment by kcbanner** [comment]
Our intention was to provide lossless TGAs that you could then convert for your own application (resize or change formats as necessary).
