### ISSUE TITLE
1 Scrap Mine reporting teamId and flags in UpperHeartlands dynamic endpoint 

### ISSUE THREAD

**Issue by QQ-q** [clapfoot/warapi#34]
![image](https://user-images.githubusercontent.com/18745182/50398278-35af7900-076e-11e9-8acf-1e4b44a8a925.png)

As you can see from the image above, there is a teamId in this scrap mine icon which does not happen with the others!!!!

**Comment by hayden-t** [comment]
So it looks like some or all of these need to be in the dynamic api, as they can be destroyed by a rocket attack, likely its just the ones in the proximity of a town hall or target, so i think we need to close a bunch of these tickets now this is sorted out.
