### ISSUE TITLE
Shipyard reports teamId and flag in UmbralWildwood

### ISSUE THREAD

**Issue by QQ-q** [clapfoot/warapi#35]
#29  The same but just want to add that it can be found in Umbralwildwood dynamic endpoint

**Comment by QQ-q** [comment]
![image](https://user-images.githubusercontent.com/18745182/50404596-b045bc00-07a1-11e9-8e42-857239671724.png)

**Comment by philipdiehl1** [comment]
This might be an unintended side effect of all build sites reporting their team, even for neutral structures.  This should be relatively harmless from a user perspective.  You can just ignore it if the build site flag is set.

I'm leaving this open for now as we may want to revisit this functionality in the future.

**Comment by QQ-q** [comment]
Since it no longer appears in the dynamic endpoint, I shall close it. 

Thank you @philipdiehl1 for looking over this issue.
