### ISSUE TITLE
please expose word conquest start time, state, win condition/state

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#4]
not super important, just a some day suggestion, oh and skirmish timer

**Comment by reilem** [comment]
This would be super helpful, since now we are getting (technically) invalid map data of warden/colonial occupation while there actually is no war on.

**Comment by hayden-t** [comment]
also related to this would be to make available number of town required to win (as this changes) and general win conditions and state.

**Comment by philipdiehl1** [comment]
This should all be supported now.
