### ISSUE TITLE
Some rocket sites both in static and dynamic api end points, such as Endless

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#40]
https://war-service-live.foxholeservices.com/api/worldconquest/maps/EndlessShore/static
![image](https://user-images.githubusercontent.com/1000743/51453327-e66f5f00-1d92-11e9-8463-2117a1102856.png)

https://war-service-live.foxholeservices.com/api/worldconquest/maps/EndlessShore/dynamic/public
![image](https://user-images.githubusercontent.com/1000743/51453334-f7b86b80-1d92-11e9-9fd6-b9981041da41.png)

**Comment by philipdiehl1** [comment]
This should be fixed now.  Most (but not all) structures will be set to dynamic now.
