### ISSUE TITLE
Rocket Site icons missing for wardens and colonials.

### ISSUE THREAD

**Issue by reilem** [clapfoot/warapi#44]

**Comment by hayden-t** [comment]
So i guess also the question is should the be reported in that api as one side or the other, as i dont think they are in game, and it could be a bug.

**Comment by reilem** [comment]
I managed to create them in photoshop using multiplied layers. Maybe I'll make a PR to include them, then others can use them if they want.

**Comment by philipdiehl1** [comment]
There aren't team specific images, just team specific RGB values:
-Colonial
- (0.082283, 0.14996, 0.07036, 1.0)
- Hex Linear: 152612FF
- Hex SRGB: 516C4BFF
-Warden
- (0.017642, 0.093059, 0.223228, 1.0)
- Hex Linear: 041739FF
- Hex SRGB: 245682FF

I'll update the readme when I get a chance.
