### ISSUE TITLE
Oarbreaker, Fisherman's Row and Tempest Island map images outdated

### ISSUE THREAD

**Issue by reilem** [clapfoot/warapi#45]
This api contains the ~~new updated~~ old images for Oarbreaker Isles, Fisherman's Row and Tempest Island. However, the (x,y) coordinates provided for map items are the ones corresponding to the ~~old~~ new maps.

![tempest](https://user-images.githubusercontent.com/11155505/52566197-6bd1b680-2e09-11e9-808d-acb2d3bc2b95.jpg)
![fishermans](https://user-images.githubusercontent.com/11155505/52566198-6c6a4d00-2e09-11e9-9149-9a24f8b3b99a.jpg)
![oarbreaker](https://user-images.githubusercontent.com/11155505/52566199-6c6a4d00-2e09-11e9-91bd-534cc7909341.jpg)

**Comment by hayden-t** [comment]
I think you'll find that the images have not been updated but the reported coords are correct, the devs have not updated them.

**Comment by philipdiehl1** [comment]
I'll make sure the maps are updated close to when 0.22 is released (as I don't know if it got updated for 0.21 even).

**Comment by hayden-t** [comment]
Correct the maps images in the repo here di not get update (but should have been)

**Comment by reilem** [comment]
My mistakes, I'm away from my desktop so I couldn't confirm in-game. I will edit the issue.

**Comment by hayden-t** [comment]
So they said they wont update till 0.22, for now we have them other ways, come into discord #code-talk channel and ask for them

**Comment by philipdiehl1** [comment]
This should be fixed now.
