### ISSUE TITLE
Rocket sites not changing ownership

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#51]
So it seems as if eg wardens start build site, and the collies come along and complete it and or use it, it is still attributed as being owned by wardens, and thus any events i attribute to it, such as launches etc, appear to be by wardens...

**Comment by hayden-t** [comment]
![image](https://user-images.githubusercontent.com/1000743/54154574-4aaac700-4496-11e9-87b5-09e23b4697b1.png)

**Comment by philipdiehl1** [comment]
This seems to be working correctly (as it's the same as every other structure).  It's likely that players don't bother destroying and rebuilding captured enemy rocket sites.
