### ISSUE TITLE
/maps/ reports DeadLandsHex but map file is MapDeadlands.tga not sure which is correct

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#57]
not a big deal but maybe convention can be aligned

**Comment by hayden-t** [comment]
otherwise all others match

**Comment by clapfootrohun** [comment]
@hayden-t Could you double check? I see the map image:  `Images/Maps/MapDeadlandsHex.TGA`

**Comment by hayden-t** [comment]
that is correct but what im saying is the api (and in game) has switched to DeadLands which seems incorrect

**Comment by clapfootrohun** [comment]
You're right, we've been inconsistent with the capitalization of `L`. We'll seek to remedy that soon after update 0.26 settles a bit.

**Comment by hayden-t** [comment]
no problem :)

**Comment by philipdiehl1** [comment]
Consolidated to one issue: https://github.com/clapfoot/warapi/issues/63
