### ISSUE TITLE
Missing "Keep" MapIcon

### ISSUE THREAD

**Issue by Sethfire** [clapfoot/warapi#58]
There seems to be a [new structure](https://user-images.githubusercontent.com/17826826/59696811-4e7d8080-921f-11e9-879b-32b816ab1795.png) similar to the Westgate Keep but I can't find the Map Icon for it. The closest was "MapIconKeepNeutral" which is the same icon as the civic center.

**Comment by hayden-t** [comment]
is this item even in the api ? what icon id ?

**Comment by hayden-t** [comment]
ah i see, marban hollow, it is the old westgate keep icon id, so yea we just need that new keep icon to replace old one

**Comment by philipdiehl1** [comment]
Icon's now been updated.
