### ISSUE TITLE
Map Icon Type 31 is missing information

### ISSUE THREAD

**Issue by Sethfire** [clapfoot/warapi#59]
Looking through the data received from WarAPI, [I have an icon of type 31 that I do not know the corresponding name of.](https://user-images.githubusercontent.com/17826826/59736960-5a545b80-928e-11e9-838d-c1960a11989e.png) 

It is not listed [in the documentation](https://user-images.githubusercontent.com/17826826/59737069-c931b480-928e-11e9-8aa9-44a644fd3ee2.png), which is why I'm opening an issue. I assume either Hayden or one of the developers will know what it is, so please let me know so that I can make appropriate updates to the War Map.

**Comment by hayden-t** [comment]
scrap mine

**Comment by hayden-t** [comment]
are they even around anymore ? maybe some are being reported by mistake

**Comment by hayden-t** [comment]
in game shows them as "salvage mine" with old scrap mine icon 
![image](https://user-images.githubusercontent.com/1000743/59738350-4b78a380-92a4-11e9-9bcc-73b8cefacae3.png)

**Comment by hayden-t** [comment]
#38 icon description in the readme should be removed, as its not used any more , and the scrap mine is now the salvage mine

**Comment by philipdiehl1** [comment]
This is due to a bug.  Salvage Mines should be using their ID (38), not the deprecated Scrap Mine ID (31).  For now, I'd recommend treating both IDs as Salvage Mines as they will use their proper ID in the next update.

**Comment by philipdiehl1** [comment]
This has now been fixed (it'll likely be in for update 28 - unless it's included in a hotfix but that's unlikely).
