### ISSUE TITLE
unique id for items ?

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#6]
Im thinking it would be good to have identifier id for each item, so that their state can be tracked between dynamic updates. As currently the only way to do this is by the position coords.

**Comment by hayden-t** [comment]
this ties into this issue https://github.com/clapfoot/warapi/issues/9

**Comment by philipdiehl1** [comment]
You could just use the X and Y position as a perfect 64 bit hash (as 2 items should never be in the exact same position).

**Comment by hayden-t** [comment]
sure this is fine
