### ISSUE TITLE
MapFlag 0x08 missing documentation

### ISSUE THREAD

**Issue by Sethfire** [clapfoot/warapi#61]
Hello. I was working on the war map today and was hunting a bug when I came across the [flag 0x08](https://i.imgur.com/mEWAVRD.png) which is undocumented in the API. Almost every fort has this flag, [but not all of them](https://i.imgur.com/0PPomyV.png) it would seem. Thanks.

**Comment by clapfootrohun** [comment]
https://github.com/clapfoot/warapi/commit/08d5130e6ecd2e2666844d00a72c4da43cc121a3 added documentation for this.

This is an internally used flag that determines whether to render the intel radius of a world map structure on the world map UI.
