### ISSUE TITLE
Bug in api /war is reporting WC number as 34 already but 34 has not started yet !!

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#65]
![image](https://user-images.githubusercontent.com/1000743/61666574-310a6d80-ad1b-11e9-9480-db52b77d679b.png)

**Comment by philipdiehl1** [comment]
I've added a warning to the documentation until this can be fixed.

**Comment by kcbanner** [comment]
This has been fixed for the next update.

**Comment by hayden-t** [comment]
great !
