### ISSUE TITLE
Data reports from offline regions

### ISSUE THREAD

**Issue by Kastow** [clapfoot/warapi#66]
When a conquest starts with some regions designated to be offline, the API still dispenses the dynamic data for them. Furthermore, the API also dispenses war reports for these from the previous war, screwing up the automated casualty counters.
For example, this is war report for Shackled Chasm on Day 1 of Conquest 34 (the region is offline):
![Screenshot_1](https://user-images.githubusercontent.com/18037126/61807764-d66c3100-ae42-11e9-9dcf-76127fcc0f02.png)

We request that there is some endpoint that shows which regions are offline for this conquest so their data is not taken into account and they are properly shown on the map as offline.

**Comment by S-i-r** [comment]
Yeah I'd like a heartbeat if at all possible too. This would go great for server status.

**Comment by hayden-t** [comment]
this is a extension of this early reported bug by me, still not fixed https://github.com/clapfoot/warapi/issues/52

**Comment by hayden-t** [comment]
no need for another endpoint, just make the data returned empty like it used to far island maps in the past

**Comment by S-i-r** [comment]
> no need for another endpoint or heartbeat, just make the data returned empty like it used to for island maps in the past

I kinda disagree with that. If it's expected for a region to be offline, an endpoint should reflect that status. In fact, all regions should have an "expected" status, perhaps a single global endpoint for the war itself with "Online, Offline, Maintenance" and so on.

A lack of data is not a good way to handle that.

**Comment by hayden-t** [comment]
disabled maps are now removed from https://war-service-live.foxholeservices.com/api/worldconquest/maps/
