### ISSUE TITLE
Change rocket site ownership to that of team which launched on launch.

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#69]
So we can report which team launched the rocket, can we change the team that owns it after launch when in scorched state to that of the team that launched.

**Comment by philipdiehl1** [comment]
- Destroyed rocket sites will now report their team id as the faction that actually launched the rocket.
This will be in the next update so I'll update the docs and close this issue when dev branch is released.

**Comment by hayden-t** [comment]
this sounds great !

**Comment by philipdiehl1** [comment]
I'll update the docs in a few min.
