### ISSUE TITLE
Static Map Data getting updated?

### ISSUE THREAD

**Issue by Afrowson** [clapfoot/warapi#77]
In the current war [WAR] I loaded the static map data request for `DeadLandsHex` on 2020-11-18 and got this:
` 
 "lastUpdated" => 1605666182324
  ,"version" => 3
`

suggesting that the **static data** got **changed 2 times** since the start. how can that be? do we have to check for static data updates during the wars?

**Comment by Afrowson** [comment]
Today, is the resistance Phase after War 65.
and i see this for the same hex:
`  "lastUpdated" => 1606634500324
  "version" => 2
`
So when do they reset and what changes?

I want to build a historic map tool, so this information would be nice. 

My project isnt live, so i cant track the changes jet.

**Comment by philipdiehl1** [comment]
It should be safe to assume that static map data doesn't change throughout the war.  You'll see the version increase every now and then if a game server restarts for any reason (usually once a week) since it always refreshes map data after restarting, but the underlying data won't have changed.
