### ISSUE TITLE
categorisation of text labels

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#9]
It would be great if you had the ability to differentiate between a town label and eg a road label. as in some cases you may only want to draw town names, or make them larger

**Comment by hayden-t** [comment]
also there is no way to associate a given text label with its icon, which ties into my other issue of a unique id for icons, and you could use this in the text too to link them

**Comment by hayden-t** [comment]
this would tie in with this issue: https://github.com/clapfoot/warapi/issues/6

**Comment by kcbanner** [comment]
Confirming that the correct way to match a label to a town is to find the closest label to that town.
